version: '3'

services:
  tomcat:
    image: tomcat:9.0.13-jre11-slim
    volumes:
      - ./app/target/helloMaven:/usr/local/tomcat/webapps/helloMaven
    ports:
      - 8080:8080
    restart: always